markdown: rdiscount
permalink: /:title/
url: http://sichenchang.github.io
name: sichenchang'blog
author: sichen
qq: 704636840
email: sichenfdu@gmail.com
duoshuo: sichen
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: http://weibo.com/704636840
github: sichenchang
pygments: true
safe: true
paginate: 20
about: "IT小菜一枚"
